line-length = 120
show-fixes = true

target-version = 'py311'

exclude = ["**/sdks/**", "**/sdk/**", "vendor/**"]

[format]
docstring-code-format = true
docstring-code-line-length = 'dynamic'
indent-style = 'space'
quote-style = 'double'

[lint]
select = ['ALL']
ignore = [
    'ANN401',  # Dynamically typed expressions (typing.Any) are disallowed in {name}
    'D',
    'D100',    # Missing docstring in public module
    'D101',    # Missing docstring in public class
    'D102',    # Missing docstring in public method
    'D103',    # Missing docstring in public function
    'D104',    # Missing docstring in public package
    'D105',    # Missing docstring in magic method
    'D107',    # Missing docstring in __init__ method
    'D205',    # One blank line required between summary line and description
    'T201',    # 'Print' found
    'TRY003',  # Specifying long messages outside the exception class (Also EM101, EM102)
    'EM101',   # Exception must not use a string literal, assign to variable first
    'S101',    # Assert detected
    'FBT001',  # Boolean-typed positional argument in function definition
    'FBT002',  # Boolean-typed default value in function definition
    'ERA001',  # Commented out code
    'TD',      # Missing issue link for this TODO, Missing author in TODO; try: `# TODO(<author_name>): ...` or `# TODO @<author_name>:
    'FIX002',  # Line contains TODO, consider resolving the issue
    'RET503',  # Missing explicit `return` at the end of function able to return non-`None` value
    'UP031',   # Use format specifiers instead of percent format
    'INP001',  # implicit-namespace-package
    'PLR0913', # Too many arguments in function definition
    'PLR2004', # Magic value used in comparison, consider using a constant
    'COM812',  # (Redundant when using formatter) missing-trailing-comma
    'S603',    # subprocess-without-shell-equals-true
    'S311',    # Standard pseudo-random generators are not suitable for cryptographic purposes
    'G004',    # logging uses f-strings
    'ANN',     # Missing type annotations
    "DTZ005",  # `datetime.datetime.now()` called without a `tz` argument
]

fixable = ['ALL']
unfixable = ['B']
extend-safe-fixes = ['D415', 'D205']

flake8-builtins.builtins-ignorelist = ['print']
flake8-quotes = { inline-quotes = 'double', multiline-quotes = 'double' }
pydocstyle = { convention = 'google' }
mccabe = { max-complexity = 14 }
pylint = { max-statements = 75 }

[lint.per-file-ignores]
"!**/src/**.py" = ["D"] # 'Docstring' rules only in src
"view/**.py" = [
    "N802",   # Allow function names in view to be camelCase
    "FBT003", #  Boolean positional value in function call
]
"**/*_widget.py" = [
    "N802",
] # Allow function names in widget files to be camelCase

[lint.flake8-annotations]
suppress-none-returning = true
allow-star-arg-any = true
